[package]
name = "scoper"
version = "0.1.0"
authors = ["Kevin Lacker <lacker@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hdf5 = "0.7.0"
